# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
latex: false
fortran: false



r_binary_packages:
  - covr
  - fs
  - officer
  - xml2
  - testthat

warnings_are_errors: false
after_success:
  - Rscript -e 'covr::codecov()'

